version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: mealyummy_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - mealyummy-net

  backend:
    build:
      context: ./meal-service
      dockerfile: Dockerfile.backend
    container_name: mealyummy_backend
    ports:
      - "127.0.0.1:8082:8082"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mealyummy-net

  frontend:
    build:
      context: ./client/client
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: https://api.mealyummy.io.vn/api/v1
        VITE_GOOGLE_CLIENT_ID: 75030109103-q0p7u9bihen5jrm73l8n3c4s8m6ihonj.apps.googleusercontent.com
    container_name: mealyummy_frontend
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mealyummy-net

networks:
  mealyummy-net:
    driver: bridge
