server:
  port: ${SERVER_PORT:8082}

spring:
  mongodb:
    uri: ${MONGODB_URI}
  application:
    name: meal-service

  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true

  data:
    web:
      pageable:
        serialization-mode: via_dto
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    mealyummy.mealservice: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    default-models-expand-depth: -1
  api-docs:
    path: /api-docs
  packagesToScan: mealyummy.mealservice.controller

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION}

# OTP Configuration
app:
  otp:
    expiration-minutes: ${OTP_EXPIRATION_MINUTES:1}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}