server:
  port: ${SERVER_PORT}

spring:
  config:
    import: optional:file:.env[.properties]
  mongodb:
    uri: ${MONGODB_URI}
  application:
    name: meal-service

  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  data:
    web:
      pageable:
        serialization-mode: via_dto
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}
    mongodb:
      auto-index-creation: true

  mail:
    host: ${MAIL_HOST:smtp-relay.brevo.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: ${MAIL_HOST:smtp-relay.brevo.com}

logging:
  level:
    org.springframework.security: DEBUG
    mealyummy.mealservice.core.security: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    mealyummy.mealservice: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    default-models-expand-depth: -1
  api-docs:
    path: /api-docs
  packagesToScan: mealyummy.mealservice.controller

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION}

# OTP Configuration
app:
  otp:
    expiration-minutes: ${OTP_EXPIRATION_MINUTES}
  client-url: ${CLIENT_URL:http://localhost:5173}

gemini:
  api:
    key: ${GEMINI_API_KEY}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# Payment Gateway Configurations
payment:
  vnpay:
    tmn-code: ${VNPAY_TMN_CODE:PLACEHOLDER}
    hash-secret: ${VNPAY_HASH_SECRET:PLACEHOLDER}
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: ${APP_URL:http://localhost:8080}/api/v1/payments/vnpay-return
  momo:
    partner-code: ${MOMO_PARTNER_CODE:PLACEHOLDER}
    access-key: ${MOMO_ACCESS_KEY:PLACEHOLDER}
    secret-key: ${MOMO_SECRET_KEY:PLACEHOLDER}
    endpoint: https://test-payment.momo.vn/v2/gateway/api/create
    return-url: ${APP_URL:http://localhost:8080}/api/v1/payments/momo-return
    notify-url: ${APP_URL:http://localhost:8080}/api/v1/payments/momo-ipn

